### ISSUE TITLE
report this content button

### ISSUE THREAD

**Issue by smrazgs** [ngds/ckanext-ngds#447]
'report this dataset' button-- report if inappropriate content; create e-mail allow comment? Hide flagged dataset--admin can respond; have a way to unpublish.

user identifies self, provid comment, might have check boxes for reasons...

have to be able to do unpublish harvested metadata

**Comment by ccaudill** [comment]
There are two issues Steve is talking about here, the Report an Issue and the Ratings. For the Ratings, here is how it currently looks at geothermaldata.org (see bottom left):

![ratingsimage](https://cloud.githubusercontent.com/assets/3188489/6511152/e53f79d6-c327-11e4-8f85-75d795dea94e.PNG)

I think Steve wants the user to be able to choose by radio button or something similar if the following statements apply:
'content not what I expected'
'doesn't include information I need'
'good enough to download'
'provides the information I need'
'wow, great stuff'
@smrazgs Please correct me if I'm wrong there.

For the Report an Issue button:
As of right now at geothermaldata.org, the Report an Issue button just goes to the ngds/metadata-issues GitHib repo:

![reportissueimage](https://cloud.githubusercontent.com/assets/3188489/6510632/7ab8447e-c324-11e4-8b21-2a693c370b4c.PNG)

@smrazgs  You want the user to actually get a form instead of creating a GitHub issue?

**Comment by smrazgs** [comment]
This has two issues. #559 covers the 'report this content' issue that started this thread.  #486 is about the ratings language, and that was apparently fixed (https://github.com/ngds/ckanext-ngds/pull/486), but the modification has been lost. In the current build there isn't even a ratings set up. I'll create new issue on ratings, and close this.

**Comment by smrazgs** [comment]
close, transfer to #559.
