### ISSUE TITLE
new UI needs 'report an issue' button

### ISSUE THREAD

**Issue by smrazgs** [ngds/ckanext-ngds#559]
need to implement the 'report an issue' feature in the new UI. (it opens a githup issue at
https://github.com/ngds/metadata-issues/issues/new

**Comment by ccaudill** [comment]
https://github.com/ngds/ckanext-ngds/issues/447
These are the same thing, correct @smrazgs ?  If so, please close this issue.

**Comment by smrazgs** [comment]
This is related to #447 but has been scaled back to just providing a way to report any issue, not only inappropriate content. I'll close #447, but keep this.  This was implemented in the V1 build e.g. see 
http://www.geothermaldata.org/dataset/geologic-map-of-the-meadview-north-quadrangle-mohave-county-arizona-and-clark-county-nevada-nbm, in the upper left, below the face book link. We need to get the functionality back.

**Comment by GaryHudmanAZGS** [comment]
This has been fixed and is working correctly. Requires the social media snippet to be included in package search, and an additional entry in the social media html block.

**Comment by smrgeoinfo** [comment]
@GaryHudmanAZGS so can this be closed?  Have updates been pushed to Github?

**Comment by GaryHudmanAZGS** [comment]
In the push to get as much done before the bucket ran dry,  I am behind on Github.  The issue is fixed in production, and I am applying to test to be able to continue on with the UI improvements.

I have a built a manifest, and have a clean virtual box that I can build a new rpm with, but not sure if that something you want me to pursue, with funding change…  Would it makes sense to do it after the completion of UI fixes so that we would have a full version release ?

Gary

**Comment by smrgeoinfo** [comment]
Let's get the gitHub synced up with all the current updates. We don't need to build a new rpm until the UI work is done. We'll want to deploy another instance for CINERGI at that point.

**Comment by GaryHudmanAZGS** [comment]
Report an Issue is in place
