### ISSUE TITLE
:  not allowed as a character in CKAN keyword

### ISSUE THREAD

**Issue by ccaudill** [ngds/ckanext-ngds#609]
![keyword-error](https://cloud.githubusercontent.com/assets/3188489/6466848/b4c17404-c187-11e4-98f8-70e48afcc384.PNG)

This is actually a big problem - can we force CKAN to accept : as part of the keyword? These https://github.com/ngds/documents/wiki/usgincm:-Content-Model-Keywords-List are the keywords we've been using to identify to CKAN the content models from harvested data in the faceted searches, but it appears that on upload, the CKAN UI is not allowing this character. 

@ykhadilkar-rei 
These would also be the keywords that the harvester function would look for to identify what content model the CSV file is in.

**Comment by smrazgs** [comment]
we have previously fixed this problem; the modification must have been lost somewhere in the code refactoring since Adrian left.  Jessica may recall something about the fix..

Stephen Richard

Chief Geoinformatics Section

Arizona Geological Survey

416 E. Congress #100, Tucson 85745

steve.richard@azgs.az.gov<mailto:steve.richard@azgs.az.gov>

520-209-4127

________________________________

**Comment by dan-olaru-reisys** [comment]
@smrazgs @jessica-azgs 
Do you guys know weather ngds/ckanext-ngds was the repository that contained the fix that got lost during code refactoring?

**Comment by jessica-azgs** [comment]
@dan-olaru-reisys Yes it was in ngds/ckanext-ngds. I just searched for the word colon in there and previous fix came up first https://github.com/ngds/ckanext-ngds/pull/433
