### ISSUE TITLE
No Data Details page link from map search results

### ISSUE THREAD

**Issue by ccaudill** [ngds/ckanext-ngds#611]
![nodatadetailspage](https://cloud.githubusercontent.com/assets/3188489/6513243/d064e370-c336-11e4-80bd-9f54c9fec7d2.PNG)

Seems to not be a way to take the user to the Data Details page!

**Comment by ccaudill** [comment]
Also to note in this list of distributions is that "Service Notifications" correctly indicates the http://notifications.usgin.org/ link, but there's also "External Website" which points to the same link and needs to be removed from the list.

**Comment by ccaudill** [comment]
When you select "Show Area on Map" there should be a way to de-select it.

**Comment by dan-olaru-reisys** [comment]
@ccaudill 
1- "Data Details Page" link has been added (its the last item in the collapsible resource list for each dataset in the results list, let me know if that works)
2- In order to deselect the "Show Area on Map" you need to click on the "Reset" button (let me know if that is acceptable)
3- 
>Also to note in this list of distributions is that "Service Notifications" correctly indicates the http://notifications.usgin.org/ link, but there's also "External Website" which points to the same link and needs to be removed from the list.

should be fixed

http://uat-ngds.reisys.com/

**Comment by smrazgs** [comment]
looking good!
